version: '3.8'

services:

  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - news-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news
      - DB_USERNAME=news_admin
      - DB_PASSWORD=news_admin_password
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: >
      sh -c "cron && php-fpm"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: news
      MYSQL_USER: news_admin
      MYSQL_PASSWORD: news_admin_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - news-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news-network
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news-network
    depends_on:
      - webserver

networks:
  news-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
